### ISSUE TITLE
Invalid configuration options

### ISSUE THREAD

**Issue by HumanMus1c** [hiddify/hiddify-next#489] opened 2024-02-16 09:18 UTC
### Search first

- [X] I searched and no similar issues were found

### What Happened?

An Alert pop up while I click "Tap to Connect", and server didn't start.
![image](https://github.com/hiddify/hiddify-next/assets/46023154/2e75dbcc-0b62-4310-b8d6-34b67428ee9f)

### Reproduce the Bug

1. click "Tap to Connect"
2. An alert pop up.
3. Server not start.

### Expected Behavior

Server start.

### Version

0.15.11 dev

### Platform/OS

Windows

### Additional Context

![image](https://github.com/hiddify/hiddify-next/assets/46023154/0d1433d6-1dff-4257-8ad3-3d36d82507b3)
[app.log](https://github.com/hiddify/hiddify-next/files/14308906/app.log)
[box.log](https://github.com/hiddify/hiddify-next/files/14308907/box.log)

### Relevant log output

```shell
17:09:17.545081 - [D] bootstrap: [logs repository] initialized in 1ms
17:09:17.545081 - [I] bootstrap: hiddify v0.15.11 (1511) [dev]
general release
windows ["Windows 10 Pro" 10.0 (Build 22631)]
17:09:17.583972 - [I] ConnectionNotifier: connection status: DISCONNECTED
17:09:17.585065 - [I] bootstrap: bootstrap took [149ms]
17:09:33.288244 - [I] UpdateProfile: successfully updated profile, was active? [true]
17:09:44.968731 - [I] ProxiesSortNotifier: sort proxies by: [delay]
17:09:46.114304 - [I] ConnectionRepositoryImpl: config options: {
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "tcp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": "10m",
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "enable-tls-fragment": false,
  "tls-fragment-size": "10-100",
  "tls-fragment-sleep": "50-200",
  "enable-tls-mixed-sni-case": false,
  "enable-tls-padding": false,
  "tls-padding-size": "100-200",
  "enable-mux": false,
  "mux-padding": false,
  "mux-max-streams": 8,
  "mux-protocol": "h2mux",
  "enable-warp": false,
  "warp-detour-mode": "outbound",
  "warp-license-key": "",
  "warp-clean-ip": "auto",
  "warp-port": 0,
  "warp-noise": "",
  "geoip-path": "geo-assets\\sagernet-sing-geoip-geoip.db",
  "geosite-path": "geo-assets\\sagernet-sing-geosite-geosite.db",
  "rules": [
    {
      "domains": "domain:.cn,geosite:cn",
      "ip": "geoip:cn",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ]
}
Memory Limit: false
17:09:46.116093 - [W] ConnectionNotifier: error connecting
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:09:46.116093 - [W] ConnectionNotifier: ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:09:46.118710 - [W] SystemTrayNotifier: error getting connection status
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:09:54.238924 - [I] ConnectionRepositoryImpl: config options: {
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "tcp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": "10m",
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "enable-tls-fragment": false,
  "tls-fragment-size": "10-100",
  "tls-fragment-sleep": "50-200",
  "enable-tls-mixed-sni-case": false,
  "enable-tls-padding": false,
  "tls-padding-size": "100-200",
  "enable-mux": false,
  "mux-padding": false,
  "mux-max-streams": 8,
  "mux-protocol": "h2mux",
  "enable-warp": false,
  "warp-detour-mode": "outbound",
  "warp-license-key": "",
  "warp-clean-ip": "auto",
  "warp-port": 0,
  "warp-noise": "",
  "geoip-path": "geo-assets\\sagernet-sing-geoip-geoip.db",
  "geosite-path": "geo-assets\\sagernet-sing-geosite-geosite.db",
  "rules": [
    {
      "domains": "domain:.cn,geosite:cn",
      "ip": "geoip:cn",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ]
}
Memory Limit: false
17:09:54.239266 - [W] ConnectionNotifier: error connecting
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:09:54.239266 - [W] ConnectionNotifier: ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:09:54.241872 - [W] SystemTrayNotifier: error getting connection status
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:12:55.317152 - [I] ConnectionRepositoryImpl: config options: {
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "tcp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": "10m",
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "enable-tls-fragment": false,
  "tls-fragment-size": "10-100",
  "tls-fragment-sleep": "50-200",
  "enable-tls-mixed-sni-case": false,
  "enable-tls-padding": false,
  "tls-padding-size": "100-200",
  "enable-mux": false,
  "mux-padding": false,
  "mux-max-streams": 8,
  "mux-protocol": "h2mux",
  "enable-warp": false,
  "warp-detour-mode": "outbound",
  "warp-license-key": "",
  "warp-clean-ip": "auto",
  "warp-port": 0,
  "warp-noise": "",
  "geoip-path": "geo-assets\\sagernet-sing-geoip-geoip.db",
  "geosite-path": "geo-assets\\sagernet-sing-geosite-geosite.db",
  "rules": [
    {
      "domains": "domain:.cn,geosite:cn",
      "ip": "geoip:cn",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ]
}
Memory Limit: false
17:12:55.317675 - [W] ConnectionNotifier: error connecting
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:12:55.317675 - [W] ConnectionNotifier: ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:12:55.322423 - [W] SystemTrayNotifier: error getting connection status
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:12:58.969400 - [I] ConnectionRepositoryImpl: config options: {
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "tcp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": "10m",
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "enable-tls-fragment": false,
  "tls-fragment-size": "10-100",
  "tls-fragment-sleep": "50-200",
  "enable-tls-mixed-sni-case": false,
  "enable-tls-padding": false,
  "tls-padding-size": "100-200",
  "enable-mux": false,
  "mux-padding": false,
  "mux-max-streams": 8,
  "mux-protocol": "h2mux",
  "enable-warp": false,
  "warp-detour-mode": "outbound",
  "warp-license-key": "",
  "warp-clean-ip": "auto",
  "warp-port": 0,
  "warp-noise": "",
  "geoip-path": "geo-assets\\sagernet-sing-geoip-geoip.db",
  "geosite-path": "geo-assets\\sagernet-sing-geosite-geosite.db",
  "rules": [
    {
      "domains": "domain:.cn,geosite:cn",
      "ip": "geoip:cn",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ]
}
Memory Limit: false
17:12:58.969849 - [W] ConnectionNotifier: error connecting
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:12:58.969849 - [W] ConnectionNotifier: ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:12:58.973330 - [W] SystemTrayNotifier: error getting connection status
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:13:26.685962 - [I] ConnectionRepositoryImpl: config options: {
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "tcp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": "10m",
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "enable-tls-fragment": false,
  "tls-fragment-size": "10-100",
  "tls-fragment-sleep": "50-200",
  "enable-tls-mixed-sni-case": false,
  "enable-tls-padding": false,
  "tls-padding-size": "100-200",
  "enable-mux": false,
  "mux-padding": false,
  "mux-max-streams": 8,
  "mux-protocol": "h2mux",
  "enable-warp": false,
  "warp-detour-mode": "outbound",
  "warp-license-key": "",
  "warp-clean-ip": "auto",
  "warp-port": 0,
  "warp-noise": "",
  "geoip-path": "geo-assets\\sagernet-sing-geoip-geoip.db",
  "geosite-path": "geo-assets\\sagernet-sing-geosite-geosite.db",
  "rules": [
    {
      "domains": "domain:.cn,geosite:cn",
      "ip": "geoip:cn",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ]
}
Memory Limit: false
17:13:26.686587 - [W] ConnectionNotifier: error connecting
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:13:26.686587 - [W] ConnectionNotifier: ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
17:13:26.691810 - [W] SystemTrayNotifier: error getting connection status
ConnectionFailure.invalidConfigOption(message: json: cannot unmarshal object into Go struct field ConfigOptions.tls-fragment-size of type string)
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by papampi** [comment] 2024-02-16 09:28
Try to reset config settings

**Comment by problematicconsumer** [comment] 2024-02-16 11:55
Duplicate of #483

**Closed by problematicconsumer** 2024-02-16 11:55 UTC
Labels: bug
