### ISSUE TITLE
Not showing IP config

### ISSUE THREAD

**Issue by Amir2367** [hiddify/hiddify-next#515] opened 2024-02-18 20:06 UTC
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In the video below, we can see that when we connect to a configuration and go back to the main page, the IP is not shown for 30 seconds and it is still loading, and then 30 seconds when it should show Germany, it shows Unknown.

https://github.com/hiddify/hiddify-next/assets/83357422/fe3c29a3-eaaa-4790-999e-bb6a5c1e1640

### Reproduce the Bug

In the video below, we can see that when we connect to a configuration and go back to the main page, the IP is not shown for 30 seconds and it is still loading, and then 30 seconds when it should show Germany, it shows Unknown.

### Version

0.16.0 dev

### Platform/OS

Android

### Additional Context

https://github.com/hiddify/hiddify-next/assets/83357422/57362ac8-2a36-4247-aefb-dd86a636ccb8

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment] 2024-02-19 08:45
Why do you keep opening issues? Duplicate of #505

**Closed by problematicconsumer** 2024-02-19 08:45 UTC
Labels: bug
