### ISSUE TITLE
Lack of VPN Profile on Mac

### ISSUE THREAD

**Issue by sghiaseddin** [hiddify/hiddify-next#495] opened 2024-02-16 21:08 UTC
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Dear Team,
On "service mode", selecting the VPN (experimental) leads to the following dialog:
`VPN mode requires administrator privileges. Either relaunch the app as administrator or change service mode.`

When I sudo the app (as root), VPN (experimental) works fine. I guess to solve this issue you need to get the permission from user and [add a VPN profile (check VPNSubType)](https://developer.apple.com/documentation/devicemanagement/vpn) in Settings > Network > VPN.

Thanks

### Reproduce the Bug

1. Change "Service Mode" into "VPN (Experimental)"
2. Connect
3. Error dialog popup: "VPN mode requires administrator privileges. Either relaunch the app as administrator or change service mode."

### Version

0.15.15 pre-release & 0.14.20 stable

### Platform/OS

macOS

### Additional Context

on MacOS 14.3
![Screenshot 1402-11-28 at 12 15 56 at night](https://github.com/hiddify/hiddify-next/assets/25960517/08c4b54e-2ef9-45b9-9c26-fcfa51cc139e)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by anon2334** [comment] 2024-02-20 15:13
### Search first
- [x]  I searched and no similar issues were found

### What Happened?
I have a similar problem as well.
### Reproduce the Bug

1. Change "Service Mode" into "VPN (Experimental)"
2. Connect
3. Error dialog popup: "VPN mode requires administrator privileges. Either relaunch the app as administrator or change service mode."

### Expected Behavior
A new window should appear, asking for the password.

### Version
Any version

### Platform/OS
macOS

### Additional Context
This is how the Nekoray app handles it:
It uses the `osascript` command:
![Screenshot 2024-02-20 at 6 10 12 PM](https://github.com/hiddify/hiddify-next/assets/68531183/84ac26a7-c581-4814-8731-efe291867c3e)

```cpp
# ui/mainwindow.cpp line 1835

vpn_process->start("osascript", {"-e", QString("do shell script \"%1\" with administrator privileges").arg("bash " + scriptPath)});

```

probably that would be something like this
```bash
osascript -e "do shell script \"'/Applications/Hiddify Next.app/Contents/MacOS/Hiddify Next'\" with administrator privileges"
```

### Relevant log output
_No response_
### Are you willing to submit a PR? If you know how to fix the bug.

- [ ]  I'm willing to submit a PR

**Comment by anon2334** [comment] 2024-02-20 15:13
### Search first
- [x]  I searched and no similar issues were found

### What Happened?
I have a similar problem as well.
### Reproduce the Bug

1. Change "Service Mode" into "VPN (Experimental)"
2. Connect
3. Error dialog popup: "VPN mode requires administrator privileges. Either relaunch the app as administrator or change service mode."

### Expected Behavior
A new window should appear, asking for the password.

### Version
Any version

### Platform/OS
macOS

### Additional Context
This is how the Nekoray app handles it:
It uses the `osascript` command:
![Screenshot 2024-02-20 at 6 10 12 PM](https://github.com/hiddify/hiddify-next/assets/68531183/84ac26a7-c581-4814-8731-efe291867c3e)

```cpp
# ui/mainwindow.cpp line 1835

vpn_process->start("osascript", {"-e", QString("do shell script \"%1\" with administrator privileges").arg("bash " + scriptPath)});

```

probably that would be something like this
```bash
osascript -e "do shell script \"'/Applications/Hiddify Next.app/Contents/MacOS/Hiddify Next'\" with administrator privileges"
```

### Relevant log output
_No response_
### Are you willing to submit a PR? If you know how to fix the bug.

- [ ]  I'm willing to submit a PR

**Comment by fantik11** [comment] 2024-02-27 18:55
+1

**Comment by fantik11** [comment] 2024-02-29 15:44
I think this error happened because we are checking if the mac application is running as root user, just like in linux privilege check [implementation](https://github.com/hiddify/hiddify-next/blob/201ea5e88dc3bd9620191bb3554b6194776cb78e/lib/features/connection/data/connection_platform_source.dart#L51). I'm not a mac os developer, but I think this can be fixed by adding "Network capability" to the macos flutter project, and changing the privilege check to something like this `if (Platform.isMacOS) {
        //Check to see if we have network capability enabled
}` so we will get the ability to use VPN mode on macos without running app as root

**Comment by zhuxining** [comment] 2024-03-01 05:38
VPN mode requires administrator privileges. Either relaunch the app as administrator or change service mode.

+1

**Comment by danialkj** [comment] 2024-03-16 09:39
VPN mode requires administrator privileges. Either relaunch the app as administrator or change service mode.

+1

**Comment by lymanjre** [comment] 2024-04-27 15:19
Open it with admin privilege. See YouTube video for more info

**Closed by lymanjre** 2024-04-27 15:19 UTC
Labels: bug

**Comment by alircxa** [comment] 2024-06-11 08:47
This workaround with sudo permissions prevents sharing the Hiddify VPN connection over my home local network using macOS Internet Sharing (the feature that lets you share your entire VPN connection as a new Wi-Fi network). Similar to iOS, please consider adding VPN profiles for macOS.

Because of this lack, I'm currently using the TestFlight beta (1.1.1) which expires in 8 days. An update is needed to prevent disabling Hiddify for everyone using the TestFlight version.

**Comment by samadariyan** [comment] 2024-07-20 13:39
> Open it with admin privilege. See YouTube video for more info

please put the link to video
